### PR TITLE
Add params.

### PR DESCRIPTION
**Pull request by eloyucu**

### CODE REVIEW

**Comment by johnhamelink** [comment]
@eloyucu Thanks for your contribution! Can you add an example of how you'd use the extra params to the usage section of the README? So others can see how to use it? Thanks 😄

**Comment by johnhamelink** [comment]
Also, adding a test would be very helpful!

**Comment by eloyucu** [comment]
Yes... I can add an example. But about the test... I can not promess you nothig... I will need to search for some xml and xslt that uses some params.
And... I am adding some guards... I´ll push in one second. 
:)

**Comment by johnhamelink** [comment]
Thanks @eloyucu, I appreciate your effort 😄

**Comment by eloyucu** [comment]
Ok!! Test are added. But I only test if there was some error or everything was going ok. I don´t test if the result of the transformation is the desired. 

I added some guards to avoid bad arguments crashing.

**Comment by eloyucu** [comment]
PS: There is a problem with the doc. The test on the doc is the only one that fails. I don´t know what it is... but I bet for the paths.

**Comment by johnhamelink** [comment]
@eloyucu brilliant, that's all we needed 😄  I will merge this for now and check out the broken test sometime soon. Thank you!

**Comment by eloyucu** [comment]
Thank you @johnhamelink 
Happy to contribute :)

**Pull request merged**
